#-Aliases for cd------------------------------------------------------------------------------------------------------------------------------------------------------------------
alias ..='cd ..; pwd'
alias cdm='cd /mnt; pwd'
alias cdd='cd /data; pwd'
alias cds='cd /data/shells; pwd'
alias cdh='cd /data/home-bb; pwd'
alias cdg='cd /data/git; pwd'
alias cdv='cd /srv/http/VNSR/VNSR'

#-Aliases for sudo----------------------------------------------------------------------------------------------------------------------------------------------------------------
alias sudo='/usr/bin/sudo'
alias off='/usr/bin/sudo poweroff'
alias res='/usr/bin/sudo reboot'

#-Aliases for listing-------------------------------------------------------------------------------------------------------------------------------------------------------------
alias lb='lsblk'
alias lf='lsblk -f'
alias lm='echo "/mnt"; ls -laF /mnt'

#-Aliases for yaourt--------------------------------------------------------------------------------------------------------------------------------------------------------------
alias ins='yaourt -S'
alias new='yaourt -Syua'
alias del='yaourt -Rsn'

alias c='clear'
alias лунюыр='key.sh'
alias OK='echo OK'
alias mv='mv -v'
alias cp='cp -v'
alias rm='rm -v'
alias scp='scp -r'

#-Aliases for systemd-------------------------------------------------------------------------------------------------------------------------------------------------------------
alias sysstat='systemctl status'
alias sysstart='sudo systemctl start'
alias sysstop='sudo systemctl stop'
alias sysen='sudo systemctl enable'
alias sysdis='sudo systemctl disable'

#-Aliases for ssh-----------------------------------------------------------------------------------------------------------------------------------------------------------------
alias server='ssh HomeServer'
alias anton='ssh AntonStacionPC'
alias ksusha='ssh KsushaNotebook'
alias home='ssh -p 5122 VlasovNetwork.sknt.ru'

#-Aliases for git-----------------------------------------------------------------------------------------------------------------------------------------------------------------
alias ga='git add'
alias gb='git branch'
alias gc='git commit -m'
alias gch='git checkout'
alias gd='git difftool'
alias gl='git log'
alias gr='git remote show origin'
alias grs='git reset'
alias gs='git status'
alias gps='git push'
alias gpl='git pull'

#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
alias kf='killall firefox'
alias feh='feh -r -F'
